export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';
export const DELETE_USER = 'DELETE_USER';
export const RESTART = 'RESTART';
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAIL = 'UPDATE_USER_DATA_FAIL';
export const ADD_REGISTER_SUCCESS = 'ADD_REGISTER_SUCCESS';
export const ADD_REGISTER_FAIL = 'ADD_REGISTER_FAIL';
export const GET_REGISTERS_FAIL = 'GET_REGISTERS_FAIL';
export const GET_REGISTERS = 'GET_REGISTERS';
export const RESTART_REGISTER = 'RESTART_REGISTER';
export const DELETE_REGISTER = 'DELETE_REGISTER';
export const SEND_REGISTER = 'SEND_REGISTER';
export const CANCEL_REGISTER = 'CANCEL_REGISTER';
export const SEND_MULTIPLE_REGISTER = 'SEND_MULTIPLE_REGISTER';
export const UPDATE_REGISTER_SUCCESS = 'UPDATE_REGISTER_SUCCESS';
export const UPDATE_REGISTER_FAIL = 'UPDATE_REGISTER_FAIL';
export const VALIDATE_REGISTER_SUCCESS = 'VALIDATE_REGISTER_SUCCESS';
export const POST_QUERY_SUCCESS = 'POST_QUERY_SUCCESS';
export const POST_QUERY_FAIL = 'POST_QUERY_FAIL';
export const POST_QUERY_WORKFORCE_SUCCESS = 'POST_QUERY_WORKFORCE_SUCCESS';
export const RESTART_USERS = 'RESTART_USERS';

export const POST_QUERY_EDIT_SUCCESS = 'POST_QUERY_EDIT_SUCCESS';
export const POST_QUERY_EDIT_FAIL = 'POST_QUERY_EDIT_FAIL';

export const RESTART_QUERY = 'RESTART_QUERY';
export const RESTART_QUERY_CLASSIFY = 'RESTART_QUERY_CLASSIFY';

export const GET_GOALS_SUCCESS = 'GET_GOALS_SUCCESS';
export const GET_GOALS_FAIL = 'GET_GOALS_FAIL';

export const POST_GOALS_SUCCESS = 'POST_GOALS_SUCCESS';
export const POST_GOALS_FAIL = 'POST_GOALS_FAIL';

export const GET_CLASSIFY_SUCCESS = 'GET_CLASSIFY_SUCCESS';
export const GET_CLASSIFY_FAIL = 'GET_CLASSIFY_FAIL';

export const UPDATE_VALIDATE_REGISTER_SUCCESS = 'UPDATE_VALIDATE_REGISTER_SUCCESS';

export const POST_CLASSIFY_SUCCESS = 'POST_CLASSIFY_SUCCESS';
export const POST_CLASSIFY_FAIL = 'POST_CLASSIFY_FAIL';
//CONSECUTIVES
export const GET_CONSECUTIVES = 'GET_CONSECUTIVES';
export const GET_CONSECUTIVES_FAIL = 'GET_CONSECUTIVES_FAIL';
export const UPSERT_CONSECUTIVES = 'UPSERT_CONSECUTIVES';
export const UPSERT_CONSECUTIVES_FAIL = 'UPSERT_CONSECUTIVES_FAIL';

export const UPDATE_DATE_REGISTER_SUCCESS = 'UPDATE_DATE_REGISTER_SUCCESS';

export const POST_AGREGGATE_SUCCESS = 'POST_AGREGGATE_SUCCESS';
export const POST_AGREGGATE_FAIL = 'POST_AGREGGATE_FAIL';

